[debug]
address = "127.0.0.1"
port = 8001
debug = 0
log_level = "critical"
workers = 16

[debug.databases.redis]
#url = "redis://127.0.0.1:6379/1"
url = "unix:///var/run/redis/redis.sock"
min_connections = 1024
max_connections = 4096
connect_timeout = 5
idle_timeout = 120
